#### Problem 1
Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

### Numpy implementation of Alexandre-Theophile Vandermonde
#### https://numpy.org/doc/stable/reference/generated/numpy.vander.html

In [1]:
import numpy as np

In [2]:
x = np.array([1, 2, 3, 5])
N = 3
np.vander(x, N)

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [25,  5,  1]])

In [3]:
np.vander(x, N, True)

array([[ 1,  1,  1],
       [ 1,  2,  4],
       [ 1,  3,  9],
       [ 1,  5, 25]])

In [4]:
np.vander(x)

array([[  1,   1,   1,   1],
       [  8,   4,   2,   1],
       [ 27,   9,   3,   1],
       [125,  25,   5,   1]])

In [5]:
# vander using comumn stack
np.column_stack([x**(N-1-i) for i in range(N)])

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [25,  5,  1]])

### Custom implementation of vander 

In [6]:
# use numpy comumn stack to append columns in matrix

'''
Parameters
    x - array_like (1-D input array.)
    N - int, optional
    increasing - bool, optional
    Order of the powers of the columns. If True, the powers increase from left to right, if False (the default) they are reversed.
'''
def custom_vender(x, N=None, increasing=False):
        if N is None:
            N = x.size
        if(increasing):
            return np.column_stack([x**i for i in range(N)])
        else:
            return np.column_stack([x**i for i in range(N-1, -1, -1)])
        

In [7]:
custom_vender(np.array([1,2,3,4]))

array([[ 1,  1,  1,  1],
       [ 8,  4,  2,  1],
       [27,  9,  3,  1],
       [64, 16,  4,  1]])

In [8]:
custom_vender(np.array([1,2,3,4]), increasing=True)

array([[ 1,  1,  1,  1],
       [ 1,  2,  4,  8],
       [ 1,  3,  9, 27],
       [ 1,  4, 16, 64]])

In [9]:
custom_vender(np.array([1,2,3,4]),N=3, increasing=True)

array([[ 1,  1,  1],
       [ 1,  2,  4],
       [ 1,  3,  9],
       [ 1,  4, 16]])

#### Problem Statement 2:

In [10]:
import numpy as np

In [11]:
# numpy has inbuilt method that takes an array and returns the average
arr = np.arange(1, 5, 1)
print(arr)
print(np.average(arr))

[1 2 3 4]
2.5


### Method for calculating moving average

In [12]:
def find__moving_avg(lst, k):
    n = len(lst)
    return [np.average(lst[i:i+k]) for i in range(n-k+1)]

In [13]:
arr1 = [10 ,20, 30, 40, 50, 60, 70, 80, 90, 100] # np.arange(10, 101, 10)
print(find__moving_avg(arr1, 4))

[25.0, 35.0, 45.0, 55.0, 65.0, 75.0, 85.0]


In [14]:
arr2 = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
print(find__moving_avg(arr2, 3))

[5.0, 4.666666666666667, 5.666666666666667, 6.666666666666667, 9.666666666666666, 28.666666666666668, 49.333333333333336, 72.66666666666667, 84.0, 93.33333333333333, 116.33333333333333]
